-- MySQL Script generated by MySQL Workbench
-- Wed Jun 12 17:07:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Tarea06DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Tarea06DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Tarea06DB` DEFAULT CHARACTER SET utf8 ;
USE `Tarea06DB` ;

-- -----------------------------------------------------
-- Table `Tarea06DB`.`Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tarea06DB`.`Cursos` (
  `idCursos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Sigla` CHAR(7) DEFAULT NULL,
  `Nombre` VARCHAR(200) NOT NULL,
  `Semestre` VARCHAR(4) DEFAULT NULL,
  `Creditos` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCursos`),
  UNIQUE INDEX `idCursos_Cursos_UNIQUE` (`idCursos` ASC) VISIBLE,
  UNIQUE INDEX `Sigla_UNIQUE` (`Sigla` ASC) VISIBLE,
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC) VISIBLE,
  INDEX `Semestre` (`Semestre` ASC) VISIBLE,
  INDEX `Creditos` (`Creditos` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea06DB`.`Requisitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tarea06DB`.`Requisitos` (
  `RequisitoID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CursoID` INT UNSIGNED NOT NULL,
  `RequisitoCursoID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`RequisitoID`),
  UNIQUE INDEX `RequisitoID_UNIQUE` (`RequisitoID` ASC) VISIBLE,
  INDEX `CursoID` (`CursoID` ASC) VISIBLE,
  INDEX `RequisitoCursoID` (`RequisitoCursoID` ASC) VISIBLE,
  CONSTRAINT `fk_Requisitos_CursoID`
    FOREIGN KEY (`CursoID`)
    REFERENCES `Tarea06DB`.`Cursos` (`idCursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Requisitos_RequisitoCursoID`
    FOREIGN KEY (`RequisitoCursoID`)
    REFERENCES `Tarea06DB`.`Cursos` (`idCursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea06DB`.`Descripciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tarea06DB`.`Descripciones` (
  `DescripcionID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CursoID` INT UNSIGNED NOT NULL,
  `Descripcion` TEXT NOT NULL,
  `Dificultad` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`DescripcionID`),
  UNIQUE INDEX `DescripcionID_UNIQUE` (`DescripcionID` ASC) VISIBLE,
  UNIQUE INDEX `CursoID_UNIQUE` (`CursoID` ASC) VISIBLE,
  FULLTEXT INDEX `Descripcion` (`Descripcion`) VISIBLE,
  INDEX `Dificultad` (`Dificultad` ASC) VISIBLE,
  CONSTRAINT `fk_Descripciones_CursoID`
    FOREIGN KEY (`CursoID`)
    REFERENCES `Tarea06DB`.`Cursos` (`idCursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `Tarea06DB`.Cursos(Sigla, Nombre, Semestre, Creditos)
VALUES ("IE-0579", "Administración de sistemas", "IX", 4),
       ("IE-0613", "Electrónica Industrial", "IX", 4),
       ("IE-0599", "Anteproyecto de TFG", "IX", 4),
       ("IE-XXXX", "Optativa I", "IX", 3),
       ("IE-YYYY", "Optativa II", "IX", 3),
       ("IE-0679", "Ciencia de datos para la est. y pron. de eventos", "X", 3),
       ("IE-ZZZZ", "Optativa III", "IX", 3),
       ("IE-WWWW", "Optativa IV", "IX", 3),
       ("IE-0541", "Seguridad ocupacional", "X", 3),
       ("", "TFG", "X", 3);
       
SELECT * FROM `Tarea06DB`.Cursos;